### PR TITLE
Initial Fuse 3 support + Support to allow some special options

### PR DESCRIPTION
**Pull request by McBane87**
To be clear in the beginning:
I cannot ensure that I did everything the right way, because I'm not really a C Programmer. 
I only have a very basic knowledge in C.

What have I done:
- Adjusted all existing functions to work with Fuse 3
- Added an special option filter. This way one can pass options like "nofail" without libfuse complaining. Such options are neccessary for systemd+fstab, but will be ignored by fuse and bindfs.

What I havn't done:
- Testing proper functionality with other OS like "OS X". 
You maybe have to finetune. I only did testing CentOS 7 so far.

### CODE REVIEW

**Comment by mpartel** [comment]
Oh wow, thanks!

I'll go through the code in detail in a few days.

Some questions in the meantime:
- Did you run the tests? (`cd tests && ./test_bindfs.rb && sudo ./test_bindfs.rb && ./test_bindfs.rb --valgrind && sudo ./test_bindfs.rb --valgrind` (which I really should simplify and document))
- Is the `renameat2` fallback implementation copied from somewhere or did you write it yourself? 
- The fallback adds quite a lot of complexity. Would it be reasonable to just not support `flags != 0` on platforms that don't have `renameat2`?

**Comment by McBane87** [comment]
> * Did you run the tests? (`cd tests && ./test_bindfs.rb && sudo ./test_bindfs.rb && ./test_bindfs.rb --valgrind && sudo ./test_bindfs.rb --valgrind` (which I really should simplify and document))

No, I wasn't aware of this. But I will do this now. 
- I already run into an error with "readdir inodes", looks like putting the options `readdir_ino` & `use_ino` into `bindfs_init` function isn't working. Unfortunately just passing them via `-o` isn't working anymore in fuse3. Those options are not known anymore.
- Also I have to recheck my `filter_special_opts` function. Running into a segfault, when it is used. Odd thing is. Some hours ago it was working somehow....

> * Is the renameat2 fallback implementation copied from somewhere or did you write it yourself?

I wrote this myself. With my basic C knowledge

> * The fallback adds quite a lot of complexity. Would it be reasonable to just not support flags != 0 on platforms that don't have renameat2?

I guess just ignoring the flags should also work. In their (libfuse) own example [passthrough.c](https://github.com/libfuse/libfuse/blob/master/example/passthrough.c), they also just ignore the flags

**Comment by McBane87** [comment]
Fixed my Segfault on `filter_special_opts` with previous commit.

**Comment by McBane87** [comment]
Regarding `readdir_ino` & `use_ino`:
Looks like setting those options in `bindfs_init` is working. But it is not possible to use both options together. So this way I will never be able to pass the test because always one of the ino tests will fail. Can I skip one of them?

fuse.h comment for readdir_ino:
> If use_ino option is given, this option is ignored.

fuse.h completely for both options:
``` c
	/**
	 * Honor the st_ino field in the functions getattr() and
	 * fill_dir(). This value is used to fill in the st_ino field
	 * in the stat(2), lstat(2), fstat(2) functions and the d_ino
	 * field in the readdir(2) function. The filesystem does not
	 * have to guarantee uniqueness, however some applications
	 * rely on this value being unique for the whole filesystem.
	 *
	 * Note that this does *not* affect the inode that libfuse 
	 * and the kernel use internally (also called the "nodeid").
	 */
	int use_ino;

	/**
	 * If use_ino option is not given, still try to fill in the
	 * d_ino field in readdir(2). If the name was previously
	 * looked up, and is still in the cache, the inode number
	 * found there will be used.  Otherwise it will be set to -1.
	 * If use_ino option is given, this option is ignored.
	 */
	int readdir_ino;
```

**Comment by mpartel** [comment]
Thanks! I'll merge this to branch `fuse3` and play around with it a bit and then get back to you.

**Comment by mpartel** [comment]
Making [progress](https://github.com/mpartel/bindfs/compare/fuse3), but not there yet.

- Will need to work around the readdir `use_ino` [problem](https://github.com/libfuse/libfuse/issues/583). Even if it's a FUSE bug, lots of distros will probably never patch it.
- Got all other tests to pass (on Debian 10 at least).
- I've not yet reviewed `filter_special_opts` properly.
- More testing, more cleanup..

I'll continue when I find a bit of time again.

**Comment by mpartel** [comment]
Released as 1.15.0!

**Pull request merged**
